# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTPInfo', '0002_auto_20160911_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='user',
            new_name='user_id',
        ),
    ]
