# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTPInfo', '0003_auto_20160911_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='user_id',
            new_name='user',
        ),
    ]
