# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 07:08
from __future__ import unicode_literals

import Projects.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=40, verbose_name='Project Title')),
                ('project_from_date', models.DateField()),
                ('project_to_date', models.DateField()),
                ('project_pic', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=Projects.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('project_handleby', models.CharField(max_length=40, verbose_name='Project Manager')),
                ('project_description', models.TextField(max_length=2000)),
                ('project_total_cost', models.PositiveIntegerField()),
                ('project_total_raised', models.PositiveIntegerField()),
                ('project_created_date', models.DateField(auto_now=True)),
                ('project_updated_date', models.DateField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.Location', verbose_name='Project Location')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAlbum',
            fields=[
                ('project_album_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_photo', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=Projects.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.Project', verbose_name='Select Project')),
            ],
        ),
    ]
