# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 10:55
from __future__ import unicode_literals

import Projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectalbum',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='projectalbum',
            name='width_field',
        ),
        migrations.AddField(
            model_name='projectalbum',
            name='project_photo_created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectalbum',
            name='project_photo_updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(default=1, upload_to=Projects.models.upload_location, verbose_name='Project Cover'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectalbum',
            name='project_photo',
            field=models.ImageField(default=1, upload_to=Projects.models.upload_location, verbose_name='Project Photo'),
            preserve_default=False,
        ),
    ]
