# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamuser', '0002_auto_20160830_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_info', models.CharField(max_length=32, verbose_name='Device Token')),
                ('device_created_date', models.DateField(auto_now=True)),
                ('device_updated_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamuser.UserInfo', verbose_name='User Name')),
            ],
        ),
    ]
