# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:42
from __future__ import unicode_literals

import NewsFeed.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
        ('gamuser', '0001_initial'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=40, verbose_name='Headlines')),
                ('news_description', models.TextField(max_length=2000)),
                ('news_image1', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=NewsFeed.models.upload_location, verbose_name='News Image 1', width_field='width_field')),
                ('news_image2', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=NewsFeed.models.upload_location, verbose_name='News Image 2', width_field='width_field')),
                ('news_image3', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=NewsFeed.models.upload_location, verbose_name='News Image 3', width_field='width_field')),
                ('news_image4', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=NewsFeed.models.upload_location, verbose_name='News Image 4', width_field='width_field')),
                ('news_image5', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=NewsFeed.models.upload_location, verbose_name='News Image 5', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('news_created_date', models.DateField(auto_now=True)),
                ('news_updated_date', models.DateField(auto_now=True)),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.Category', verbose_name='Select Category')),
                ('news_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.Location', verbose_name='News Location')),
            ],
        ),
        migrations.CreateModel(
            name='NewsStatus',
            fields=[
                ('news_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_comment', models.CharField(blank=True, max_length=200)),
                ('news_status_date', models.DateField(auto_now=True)),
                ('news_status', models.CharField(choices=[('1', 'Comment'), ('2', 'Like')], max_length=2)),
                ('news_status_created_date', models.DateField(auto_now=True)),
                ('news_status_updated_date', models.DateField(auto_now=True)),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsFeed.NewsFeed', verbose_name='Select News')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamuser.UserInfo', verbose_name='Select User')),
            ],
        ),
    ]
