# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 11:36
from __future__ import unicode_literals

import NewsFeed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeed',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='newsfeed',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='news_image1',
            field=models.ImageField(default=1, upload_to=NewsFeed.models.upload_location, verbose_name='News Image 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='news_image2',
            field=models.ImageField(default=1, upload_to=NewsFeed.models.upload_location, verbose_name='News Image 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='news_image3',
            field=models.ImageField(default=1, upload_to=NewsFeed.models.upload_location, verbose_name='News Image 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='news_image4',
            field=models.ImageField(default=1, upload_to=NewsFeed.models.upload_location, verbose_name='News Image 4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='news_image5',
            field=models.ImageField(default=1, upload_to=NewsFeed.models.upload_location, verbose_name='News Image 5'),
            preserve_default=False,
        ),
    ]
