# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import gamuser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_firstname', models.CharField(max_length=20, verbose_name='First Name')),
                ('user_lastname', models.CharField(max_length=20, verbose_name='Last Name')),
                ('user_email', models.EmailField(max_length=50, verbose_name='Email Id')),
                ('user_dob', models.DateField(verbose_name='Date of Birth')),
                ('user_mobileno', models.CharField(max_length=14, verbose_name='Contact No')),
                ('user_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=gamuser.models.upload_location, verbose_name='Profile Picture', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('user_password', models.CharField(max_length=20, verbose_name='Password')),
                ('user_profession', models.CharField(max_length=20, verbose_name='Profession')),
                ('user_random_id', models.CharField(max_length=20, verbose_name='Registration Id')),
            ],
        ),
    ]
