# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
        ('gamuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_blood_group',
            field=models.CharField(default=1, max_length=5, verbose_name='Blood Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_fb_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Facebook Contact'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_location_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Location.Location', verbose_name='Current Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
