# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import gamuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('gamuser', '0002_auto_20160830_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_image',
            field=models.ImageField(default=1, upload_to=gamuser.models.upload_location, verbose_name='Profile Picture'),
            preserve_default=False,
        ),
    ]
