# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:42
from __future__ import unicode_literals

import Events.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=20, verbose_name='Event Title')),
                ('event_from_date', models.DateTimeField(verbose_name='Event From')),
                ('event_to_date', models.DateTimeField(verbose_name='Event To')),
                ('event_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=Events.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('event_organized_by', models.CharField(max_length=50, verbose_name='Organizers')),
                ('event_address', models.CharField(max_length=150, verbose_name='Address')),
                ('event_chief_guest', models.CharField(max_length=50, verbose_name='Chief Guest')),
                ('event_description', models.TextField(max_length=2000)),
                ('event_created_date', models.DateField(auto_now=True)),
                ('event_updated_date', models.DateField(auto_now=True)),
                ('event_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.Location', verbose_name='Event Location')),
            ],
        ),
    ]
