# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 13:44
from __future__ import unicode_literals

import Events.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAlbum',
            fields=[
                ('event_album_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_photo', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=Events.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.Event')),
            ],
        ),
    ]
