# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_eventalbum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventalbum',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.Event', verbose_name='Select Event'),
        ),
    ]
