# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20160830_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventalbum',
            old_name='event_id',
            new_name='event',
        ),
    ]
