# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 14:10
from __future__ import unicode_literals

import Events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_eventstatusofuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='event',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default=1, upload_to=Events.models.upload_location, verbose_name='Event Poster'),
            preserve_default=False,
        ),
    ]
