# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_eventstatusofuser_event_status_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventalbum',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='eventstatusofuser',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='eventstatusofuser',
            old_name='user',
            new_name='user_id',
        ),
    ]
