# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0009_auto_20160910_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatusofuser',
            name='event_user_status',
            field=models.CharField(choices=[('1', 'Going'), ('2', 'Interested'), ('3', 'Maybe')], default=1, max_length=3),
        ),
    ]
