# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=30)),
                ('location_created_date', models.DateField(auto_now=True)),
                ('location_updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
